[package]
name = "set-1"
version = "0.1.0"
authors = ["Walter Smuts <wssmts@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
hex = "0.4"
openssl = "0.10"
